apiVersion: batch/v1
kind: CronJob
metadata:
  name: slack-vsphere-cpu-notification
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: notification
            volumeMounts:
            - name: vcenter-credential
              mountPath: /var/run/secret/vcenter
              readOnly: true
            env:
            - name: VCENTER_SECRET_PATH
              value: /var/run/secret/vcenter/creds.xml
            - name: VCENTER_URI
              value: "vcenter.sddc-44-236-21-251.vmwarevmc.com"
            - name: SLACK_WEBHOOK_URI
              valueFrom:
                secretKeyRef:
                  name: slack-webhook-uri
                  key: uri
            image: busybox
            imagePullPolicy: Always
            command:
            - /bin/pwsh
            - -f
            - .\notifications.ps1
          restartPolicy: Never
          volumes:
          - name: vcenter-credential
            secret:
              secretName: vcenter-credential
