apiVersion: apps/v1
kind: Deployment
metadata:
  name: powershell-testing
  namespace: vsphere-alerts
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: powershell-testing
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: powershell-testing
    spec:
      containers:
      - args:
        - /bin/pwsh
        - -Command
        - Get-Content /dev/null -Wait
        env:
        - name: SLACK_WEBHOOK_URI
          valueFrom:
            secretKeyRef:
              key: uri
              name: slack-webhook-uri
        image: quay.io/jcallen/vsphere-slack-notify:latest
        imagePullPolicy: Always
        name: powershell
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/secret/vcenter
          name: vcenter-credentials
          readOnly: true
        - mountPath: /var/run/config/vcenter
          name: vcenter-configs
          readOnly: true
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - vcs8e-vc.ocp2.dev.cluster.com
        ip: 192.168.133.73
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vcenter-credentials
        secret:
          defaultMode: 420
          secretName: vcenter-credentials
      - name: vcenter-configs
        configMap:
          name: vcenter-configs
