apiVersion: batch/v1
kind: CronJob
metadata:
  name: ibm-slack-vsphere-cleanup-notification
  namespace: vsphere-alerts
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - args:
            - /bin/pwsh
            - -File
            - /projects/cleanup.ps1
            env:
            - name: VCENTER_SECRET_PATH
              value: /var/run/secret/vcenter/creds.xml
            - name: VCENTER_URI
              value: ibmvcenter.vmc-ci.devcluster.openshift.com
            - name: KUBEVOL_DATASTORE
              value: vsanDatastore
            - name: GOVC_DATACENTER
              value: IBMCloud
            - name: GOVC_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: ibm-govc-credential
            - name: GOVC_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: ibm-govc-credential
            - name: SLACK_WEBHOOK_URI
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: slack-webhook-uri
            image: quay.io/jcallen/vsphere-slack-notify:latest
            imagePullPolicy: Always
            name: notification
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /var/run/secret/vcenter
              name: vcenter-credential
              readOnly: true
          dnsPolicy: ClusterFirst
          hostAliases:
          - hostnames:
            - vcs8e-vc.ocp2.dev.cluster.com
            ip: 192.168.133.73
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - name: vcenter-credential
            secret:
              defaultMode: 420
              secretName: ibm-vcenter-credential
  schedule: 0 0 */3 * *
  successfulJobsHistoryLimit: 1
