kind: PersistentVolumeClaim
metadata:
  name: debug-dhcp-pvc
  namespace: vsphere-alerts
spec:
  storageClassName: gp3-csi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
